### ISSUE TITLE
Disable Node update

### ISSUE THREAD

**Issue by Timothy-Liuxf** [eesast/docs#399]
近期发现 `master` 分支 deploy ci 失败，查看 log 发现，第一次失败来自 #324 的 merge 之后的 [`deploy #722`](https://github.com/eesast/docs/runs/3956730585?check_suite_focus=true)，所做的更改是将 Node 16 升级为了 Node 17。  

目前我在 #397 中恢复了 Node 16，并在 #398 中禁用了 renovate 的 Node 自动更新作为权宜之计，此问题等待解决。

**Comment by L0510410** [comment]
@all-contributors please add @L0510410  @TCL606  @BryantSuen @wang-zh20 @chen-yy20 for doc

**Comment by L0510410** [comment]
@all-contributors please add @TCL606,@BryantSuen,@wang-zh20,@chen-yy20 for doc

**Comment by L0510410** [comment]
https://github.com/all-contributors please add @TCL606, @BryantSuen, @wang-zh20, @chen-yy20 for doc

**Comment by L0510410** [comment]
@all-contributors please add @TCL606, @BryantSuen, @wang-zh20, @chen-yy20 for doc

**Comment by L0510410** [comment]
@all-contributors please add @BryantSuen for doc

**Comment by L0510410** [comment]
@all-contributors please add @TCL606 for doc
@all-contributors please add @wang-zh20 for doc
@all-contributors please add @chen-yy20 for doc

**Comment by L0510410** [comment]
@all-contributors please add @TCL606 for doc
 and please add @wang-zh20 for doc
 and please add @chen-yy20 for doc

**Comment by L0510410** [comment]
@all-contributors please add @TCL606 for doc

**Comment by L0510410** [comment]
@all-contributors please add @wang-zh20 for doc

**Comment by L0510410** [comment]
@all-contributors please add @chen-yy20 for doc

**Comment by L0510410** [comment]
@all-contributors please add @Ther-nullptr for doc

**Comment by L0510410** [comment]
@all-contributors please add @birdx-007 for doc

**Comment by L0510410** [comment]
@all-contributors please add @PLUTO-SCY for doc

**Comment by L0510410** [comment]
@all-contributors please add @L0510410 for code and maintenance

**Comment by L0510410** [comment]
@all-contributors please add @PLUTO-SCY for doc

**Comment by L0510410** [comment]
@all-contributors please add @PLUTO-SCY for doc
